[package]
name = "httpui"
version = "0.0.1"
edition = "2021"

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
env_logger = "0.10.0"
hyper = "0.14.27"
log = { version = "0.4.20", features = [] }
reqwest = { version = "0.11.20", features = ["blocking"] }
